language: node_js
node_js:
  - "6"
  - "7"
git:
  submodules: false

install: npm install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d8e7c72c5054b864646
    on_success: change
    on_failure: always
    on_start: never

after_success:
  - npm run test-cover && npm run coveralls

